.TH RUNASUSER 1 "September 29, 2010" 
.SH NAME 
runasuser - Execute programs as a specified user.

.SH SYNOPSIS 
runasuser <user> <program> [args ...]

.SH DESCRIPTION 
Run programs as a specified user as permitted via a config file.

.TP
.B user
The user you wish to run as.
.TP
.B program
The prgram you wish to run.
.TP
.B args
The arguments to the program if any.

.SH SEE ALSO
	runasuser.conf(5)

.SH SOURCE
Source available at http://github.com/ac000/runasuser under the GNU GPLv2

.SH AUTHORS
Andrew Clayton <andrew@digital-domain.net>

