.TH RUNASUSER.ENV.CONF 5 "March 15, 2011" 
.SH NAME 
runasuser.env.conf - runasuser environment configuration file

.SH DESCRIPTION 
.B runasuser.env.conf
is a text file that contains a list of users and their environment settings.

It contains one line per user that specifies the user and then a comma
separated list of environment settings.

.RS
to_user	TERM=linux,LANG=en_GB.UTF-8

.RE
to_user and the environment list can separated by spaces or tabs.
See runasuser.env.conf.example

.SH SEE ALSO
	runasuser(1)

