.TH RUNASUSER 1 "March 15, 2011"
.SH NAME 
runasuser - Execute programs as a specified user.

.SH SYNOPSIS 
runasuser <user> <program> [args ...]

.SH DESCRIPTION 
Run programs as a specified user as permitted via a config file.

.TP 12
.B user
The user you wish to run as.
.TP 12
.B program
The prgram you wish to run.
.TP 12
.B args
The arguments to the program if any.

.SH "ENVIRONMENT VARIABLES"
.TP 20
RUNASUSER_CHDIR
This controls whether or not runasuser will chdir(2) into the users home
directory.

The default is to chdir. If set to 0, runasuser will not chdir.

.SH FILES
.TP 35
.B /etc/runasuser.conf
runasuser configuration file
.TP 35
.B /usr/local/etc/runasuser.conf
runasuser configuration file
.TP 35
.B /etc/runasuser.env.conf
runasuser environment configuration file
.TP 35
.B /usr/local/etc/runasuser.env.conf
runasuser environment configuration file

.SH "SEE ALSO"
runasuser.conf(5) runasuser.env.conf(5)

.SH SOURCE
Source available at http://github.com/ac000/runasuser under the GNU GPLv2

.SH AUTHORS
Andrew Clayton <andrew@digital-domain.net>

